# Main settings
title: "ML"
author: "Arabov Mullosharaf"
logo: ""

# HTML options
html:
  favicon: ""
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

repository:
  url: https://github.com/username/mycourse
  branch: main
  path_to_book: ""
