name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:       # <- ДОБАВЬТЕ ЭТУ СТРОКУ!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book ghp-import
        pip install numpy matplotlib

    - name: Build Jupyter Book
      run: |
        jupyter-book build --keep-going --all . 2>&1 | tee build.log

    - name: Show build log (for debugging)
      run: |
        cat build.log

    - name: Deploy to GitHub Pages
      run: |
        ghp-import --no-jekyll --push --force _build/html
